on:
  push:
    branches-ignore:
      - gh-pages

name: check-project

jobs:
  check-src:
    runs-on: ubuntu-24.04
    name: "check project with checklist"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"

    permissions:
      contents: read

    steps:

      - name: "Check project with checklist"
        uses: inbo/actions/check_project@composite
